[versions]
kordex = "1.6.1"

[plugins]
kordex = { id = "dev.kordex.gradle.kordex", version.ref = "kordex" }

[libraries]
kord-extensions = { module = "dev.kordex:kord-extensions", version.ref = "kordex" }