[versions]
discordkt = "271f8ebe79" # this is from jitpack.io
coroutines = "1.10.2"
dotenv = "6.4.2"

[libraries]
discordkt = { module = "com.github.MayaChen350:discordkt", version.ref = "discordkt" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
dotenv = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv"}